Adding contributing guide
prismicio/ruby-kit pull request #111
Opened 2021-06-02 15:14 UTC by faresd

Adding contributing & linking to it
removing some dead code.

2021-06-03 11:50 UTC, phillysnow commented
Here's my suggested edits @faresd, what do you think?

[![Gem Version](https://badge.fury.io/rb/prismic.io.png)](http://badge.fury.io/rb/prismic.io)
[![Build Status](https://api.travis-ci.org/prismicio/ruby-kit.png)](https://travis-ci.org/prismicio/ruby-kit)

## How to contribute to this kit

### Did you find a bug?

* **Do not open up a GitHub issue if the bug is a security vulnerability
  in the kit**, and instead, email us at [security@prismic.io](security@prismic.io).

* **Ensure the bug was not already reported** by searching on GitHub under [Issues](https://github.com/faresd/ruby-kit/issues).

* If you're unable to find an open issue addressing the problem, [open a new one](https://github.com/faresd/ruby-kit/issues/new). Be sure to include a **title and clear description**, as much relevant information as possible, and a **code sample** or an **executable test case** demonstrating the expected behaviour that is not occurring.

### Did you write a patch that fixes a bug?

* Open a new GitHub pull request with the patch.

* Ensure the PR description clearly describes the problem and solution. Include the relevant issue number if applicable.

* Link the PR to any open issues that it resolves.

### Did you fix whitespace, format code, or make a purely cosmetic patch?

* Open a new GitHub pull request with the change plus a small description and the team will verify/merge.

### Do you want to add or request a new feature/update?

* Please create PR in Github with the tag [RFC] to begin a conversation about a new feature. (GitHub issues are primarily intended for bug reports and fixes.) 

* Do not submit any code to GitHub until you have collected positive feedback about the change.

### How do I make a PR?

* If you want to learn how to make a PR then follow [this freeCodeCamp guide to making your first PR](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/).

### Do you want to help review and merge PR's?

* If you want to get involved in the maintenance of this kit, then you can request to become an admin on the project by messaging the Education Team on our [community forum](https://community.prismic.io/).

Thanks!

2021-06-16 08:55 UTC, MarcMcIntosh requested changes

2021-06-16 15:44 UTC, faresd reviewed
Modified file name

2021-06-16 15:44 UTC, faresd commented on contributing.md
> +Thanks!
Yes, I've changed the file name to cap

2021-06-16 16:10 UTC, merged